-- Remarks LIST OF HUMAN RESOUCES INVOLVED IN A PARTICULAR PROJECTS

CREATE OR REPLACE FUNCTION 
GET_HUMAN_RESOURCES_FOR_PROJECT(
	p_project_id IN NUMBER
)
RETURN SYS_REFCURSOR
AS
	v_cursor SYS_REFCURSOR;
BEGIN 
	OPEN v_cursor FOR
	SELECT *
	FROM HUMAN_RESOURCE
	WHERE PROJECT_ID = p_project_id;


	RETURN v_cursor;
END GET_HUMAN_RESOURCES_FOR_PROJECT;
/