-- REMARKS ADD_PROJECT_REVIEW - to add a project review



CREATE OR REPLACE PROCEDURE ADD_PROJECT_REVIEW (
    p_PROJECT_ID NUMBER,
    p_DATE_OF_REVIEW DATE,
    p_REVIEWED_BY VARCHAR2,
    p_COMMENT1 VARCHAR2,
    p_NEXT_REVIEW_DATE DATE,
    p_REMARKS VARCHAR2
) AS
    v_REVIEW_ID NUMBER;
BEGIN
    SELECT NVL(MAX(REVIEW_ID), 0) + 1 INTO v_REVIEW_ID FROM PROJECT_REVIEW;
    
    INSERT INTO PROJECT_REVIEW (
        REVIEW_ID,
        PROJECT_ID,
        DATE_OF_REVIEW,
        REVIEWED_BY,
        COMMENT1,
        NEXT_REVIEW_DATE,
        REMARKS
    ) VALUES (
        v_REVIEW_ID,
        p_PROJECT_ID,
        p_DATE_OF_REVIEW,
        p_REVIEWED_BY,
        p_COMMENT1,
        p_NEXT_REVIEW_DATE,
        p_REMARKS
    );
    
    COMMIT;
END ADD_PROJECT_REVIEW;
/
