--REAMRKS CHANGE_PROPOSED_BUDGET - change the buddget proposed for a particular project

CREATE OR REPLACE PROCEDURE
CHANGE_PROPOSED_BUDGET(
	p_PROPOSAL_ID IN NUMBER,
	p_NEW_PROPOSED_BUDGET IN NUMBER
) AS
BEGIN
	UPDATE PROPOSAL_TABLE
	SET PROPOSED_BUDGET = p_NEW_PROPOSED_BUDGET
	WHERE PROPOSAL_ID = p_PROPOSAL_ID;

	COMMIT;
END CHANGE_PROPOSED_BUDGET;
/
