-- REMARKS INSERT_PAYMENT - insert a payment for a particluar project

CREATE OR REPLACE PROCEDURE INSERT_PAYMENT (
    p_PAYMENT_REQUEST_ID NUMBER,
    p_DATE_OF_PAYMENT DATE,
    p_AMOUNT_OF_PAYMENT NUMBER,
    p_MODE_OF_PAYMENT VARCHAR2,
    p_PAYMENT_DESCRIPTION VARCHAR2
) AS
    v_NEXT_ID NUMBER;
BEGIN
    SELECT NVL(MAX(PAYMENT_ID), 0) + 1 INTO v_NEXT_ID FROM PAYMENT;

    INSERT INTO PAYMENT (
        PAYMENT_ID,
        PAYMENT_REQUEST_ID,
        DATE_OF_PAYMENT,
        AMOUNT_OF_PAYMENT,
        MODE_OF_PAYMENT,
        PAYMENT_DESCRIPTION
    ) VALUES (
        v_NEXT_ID,
        p_PAYMENT_REQUEST_ID,
        p_DATE_OF_PAYMENT,
        p_AMOUNT_OF_PAYMENT,
        p_MODE_OF_PAYMENT,
        p_PAYMENT_DESCRIPTION
    );

    COMMIT;
END;
/
