-- REMARKS INSERT_PROJECT - insert a new project

CREATE OR REPLACE PROCEDURE 
INSERT_PROJECT (
    p_PROPOSAL_ID NUMBER,
    p_APPROVED_BUDGET NUMBER,
    p_APPROVED_DURATION VARCHAR2,
    p_STATUS VARCHAR2 DEFAULT 'ONGOING'
) AS
	v_PROJECT_ID NUMBER;
BEGIN
	SELECT Max(PROJECT_ID)+1 INTO v_PROJECT_ID FROM PROJECT;
    
INSERT INTO PROJECT (
	PROJECT_ID,
	PROPOSAL_ID,
        APPROVED_BUDGET,
        APPROVED_DURATION,
        STATUS
) VALUES (
	v_PROJECT_ID,
        p_PROPOSAL_Id,
        p_APPROVED_BUDGET,
        p_APPROVED_DURATION,
        p_STATUS
);
    
    COMMIT;
END INSERT_PROJECT;
/



