-- REMARKS UPDATE_HUMAN_RESOURCE - update the human resource for a particular project


CREATE OR REPLACE PROCEDURE UPDATE_HUMAN_RESOURCE (
    p_RESOURCE_ID NUMBER,
    p_PROJECT_ID NUMBER,
    p_EMP_ID NUMBER,
    p_ROLE_OF_EMP_PARTICULARPROJECT VARCHAR2,
    p_REMARKS VARCHAR2
) AS
BEGIN
    UPDATE HUMAN_RESOURCE
    SET
        PROJECT_ID = p_PROJECT_ID,
        EMP_ID = p_EMP_ID,
        ROLE_OF_EMP_PARTICULARPROJECT = p_ROLE_OF_EMP_PARTICULARPROJECT,
        REMARKS = p_REMARKS
    WHERE RESOURCE_ID = p_RESOURCE_ID;
    
    COMMIT;
END UPDATE_HUMAN_RESOURCE;
/
