-- REMARKS UPDATE_PROPOSAL -  UPDATE THE PROPOSAL

CREATE OR REPLACE PROCEDURE 
UPDATE_PROPOSAL (
    p_EMP_ID NUMBER,
    p_PROPOSAL_DATE DATE,
    p_PROPOSED_OUTCOME VARCHAR2,
    p_PROPOSED_DURATION VARCHAR2,
    p_HUMAN_RESOURCE NUMBER,
    p_PROPOSED_BUDGET NUMBER,
    p_STATUS VARCHAR2,
    p_APPROVED_BY VARCHAR2,
    p_DATE_OF_APPROVAL DATE,
    p_REMARKS VARCHAR2
) AS
	v_PROPOSAL_ID NUMBER;
BEGIN
	SELECT Max(PROPOSAL_ID)+1 INTO v_PROPOSAL_ID FROM PROPOSAL_TABLE;
    
INSERT INTO PROPOSAL_TABLE (
	PROPOSAL_ID,
        EMP_ID,
        PROPOSAL_DATE,
        PROPOSED_OUTCOME,
        PROPOSED_DURATION,
        HUMAN_RESOURCE,
        PROPOSED_BUDGET,
        STATUS,
        APPROVED_BY,
        DATE_OF_APPROVAL,
        REMARKS
) VALUES (
	v_PROPOSAL_ID,
        p_EMP_ID,
        p_PROPOSAL_DATE,
        p_PROPOSED_OUTCOME,
        p_PROPOSED_DURATION,
        p_HUMAN_RESOURCE,
        p_PROPOSED_BUDGET,
        p_STATUS,
        p_APPROVED_BY,
        p_DATE_OF_APPROVAL,
        p_REMARKS
);
    
    COMMIT;
END UPDATE_PROPOSAL;
/
